---
normalization_values:
  IMAGE_SIZE : 144
  SCALE_IMAGES_VALUE : 4578.9688
  SCALE_PARAMETERS : 13.9984
  SCALE_KSSW : 100
  SCALE_MT : 27.27
  SCALE_B0 : 2.7
  SCALE_B1 : 3.4944
  SCALE_T1 : 10000
  SCALE_T2 : 1000

model_parameters:
  PATCH_SIZE : 9
  EMBEDDING_DIM : 768
  DROPOUT : 0
  NUM_TRANSFORMER_LAYERES : 3
  MLP_SIZE : 3072
  NUM_HEADS : 4
  SEQUENCE_LEN : 6
  IMAGE_SIZE : 144

